version: '3.8'

services:

  typescript-node:
    container_name: typescript-node
    image: mcr.microsoft.com/devcontainers/typescript-node
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - typescript_node_data:/home/node/app
    environment:
      - NODE_ENV=development

volumes:
  typescript_node_data: